// Acquired from https://www.mariowiki.com/List_of_Luigi%27s_Mansion_quotes
export const egadd_quotes = [
    "I'm getting too old for this ghost-catching tomfoolery.",
    "Anyway, nice to meet you. I'm Professor E. Gadd.",
    "I swear, this house seems to have more and more ghosts every day!",
    "Alright, youngster! Look lively! Follow me, posthaste!",
    "So your name's Luigi? I think our paths were destined to cross. Well met, Luigi.",
    "Hmmm? Where's this, you ask? Why, these cozy quarters are where I do my ghost-studying. Professor E. Gadd's Ghost research laboratory! The Lab, if you're of a shortening mind.",
    "You won this mansion in a contest you didn't even enter? Sounds pretty fishy to me... So, you believe the mansion actually exists, then... Strange.",
    "I've been living here since I was a lad of twenty or so, and I'll tell you: That mansion appeared just a few days ago! The spirits have fooled you!",
    "I don't know if it's a dream, an illusion, or what-all, but I surely wouldn't be too happy winning a haunted house!",
    "Now that I get a look at you, I just recalled... A guy with a red hat kind of like yours went up to the mansion without even stopping to chat... and he never returned. Was he a dream, too?",
    "What? That guy was your brother? Oh no! That's horrible! He wouldn't stand a chance against those ghosts without my help! You have to go after him!",
    "Here's the plan: I'll teach you to deal with ghosts so you can rescue your brother, Luigi.",
    "I detect spirits stronger than we've yet seen lurking ahead. I think...it must be some of those escaped gallery ghosts!",
    "You know that they're really different from the other ghosts you've seen so far. They don't show their hearts very easily. Nope, not at all.",
    "When you find one, you should first use the X Button to search its heart for clues. Sometimes you can learn the best way to surprise 'em",
    "Well, Luigi, I keep my fingers crossed for you.",
    "Oh, thank goodness you're OK! I lost contact with you all of a sudden...I was a tad worried.",
    "Hmm. You seem to be a bit tuckered out after that long battle, don't you?",
    "Why don't you come back to the lab? When you vacuum a Boss ghost, your Poltergust 3000 gets pretty much full to bursting.",
    "But...ho ho...I guess you showed that boss ghost who's boss!",
    "Take a gander at this. This fine piece of work nearly twenty years to develop! I call it the Ghost Portrificationizer. This machine lets us turn the ghosts you catch into paintings. Not only that, it works in reverse, too!",
    "Hm? How do you use it, you ask? Well, it's simple. Just plug that Poltergust 3000 into that slot and enjoy the ride, my boy!",
    "The ghosts are invisible...so we need to...press them into visible forms and presto! Beautiful ghost portraits!",
    "Heh heh heh! Looks like you've run into a bit of trouble there. Maybe you need more training!",
    "There are some ghosts who'll try to grab and hold you...When that happens, try moving your Control stick back and forth to shake 'em off!",
    "It's the age old struggle for survival, my boy! Don't lose heart, Luigi!",
    "That was them! Those were the ones who released all of the ghosts from the paintings in my gallery! Those fiends!",
    "I wondered where King Boo and his gang had gone. So, they were hiding the mansion all along...Thanks for flushing 'em out, Luigi.",
    "I'm tickled you found 'em but...perhaps it would've been better if you hadn't, well...let every single one escape. Just a thought.",
    "Ah well, water under the bridge. Anyway, you should probably come back to the lab for a sec.",
    "I've been waiting for you, young Luigi.",
    "Your brother must've been taken by that gang of Boos...Poor feller...",
    "Oh now, don't talk crazy. They're not gonna eat the man.",
    "But what became of him, hm? Odd that he hasn't come back.",
    "Common theory holds that Boos grow in strength when they travel in numbers. They must somehow combine their powers too...Their power likely overwhelmed your brother.",
    "If your aim is to save Mario, there's but one way to do it: capture each Boo and slowly weaken the group's power!",
    "But Boos, as their name implies, like to hide and then jump out to scare people. You've got your work cut out finding 'em...",
    "Heh heh heh. Don't get all down in the mouth, my boy! That Game Boy Horror I gave you has a secret function! I knew it's come in handy one day, so I developed it secretly. I call it the Boo Radar.",
    "The Boo Radar will flash red when something round like a Boo is hidden nearby. Use it search everywhere, Luigi!",
    "All right now, sonny. Don't go tuckering yourself out. Relax, and just try to get those Boos one at a time. The trick is using the Control Stick and C Stick together. Don't forget, now!",
    "Mercy! You've already caught your first Boo! I've been researching those guys...",
    "Well these Boos don't seem to like light much, that's for sure. They do their best to hide in and under furniture when they're stuck in a lit room.",
    "So then I reckon that turning on all the lights in the mansion is the fastest way to find all of the Boos. Wouldn't you say, youngster?",
    "Okay, now send me the Boo and all the data you've got.",
    "It's like you were born to capture Boos, Luigi!",
    "Ho! You're on FIRE, Luigi! ON FIRE!",
    "Unbelievable! There's no stopping you, Luigi!",
    "You've already found five Boos! You're a Boo-snaring maniac!",
    "I understand you're worried about your brother, young feller, but just take 'er easy. You have plenty of time still, so try to keep your shirt on.",
    "Why not go to the Washroom and splash some water on your face? You'll feel much better, believe you me!",
    "Aren't you just loving my brilliant inventions?",
    "Hey now, Luigi! What have you found there? Let's take a look at that.",
    "...Ohh...Ahh...It's...a Fire Elemental Medal! Now you can use the Fire Element!",
    "Yes sir, with that, you can catch Fire Elemental Ghosts!",
    "Hm? What's a Fire Elemental Ghost, you ask? Why, they show up whenever you see fire, my boy! They're ghosts of fire itself, if you will.",
    "If you approach a flame, they'll be surprised by your presence and leap out into the air. Then you vacuum 'em up right away! After that, you can expel fire with the L Button. You can melt ice, light candles, do all kinds of stuff.",
    "A meter will appear down at the bottom of the screen, so keep an eye on how much element you have left, OK, feller?",
    "You may have to use the Fire Element to defeat some ghosts...Keep that in mind, sonny! Don't say I never warned you!",
    "You're doing great, Luigi!",
    "Fantastic! Way to go, Luigi!",
    "Hey now, Luigi! Now what have you stumbled across?...Ohh...This time...It's...a Water Elemental Medal!",
    "Now you can use the Water Element! My research shows that these particular Elemental Ghosts leave their watery dwellings whenever you approach. You know the drill, vacuum 'em up!",
    "I hear there are some ghosts who can be defeated only with water, actually...Also remember water has purifying properties, so use it well...",
    "Don't get caught up with your new squirt gun, Luigi!",
    "Good to hear you're still OK! I list signal when that lightning struck.",
    "Hmm. That was some battle you had there. Why don't you come on back to the lab?",
    "What? You think the lightning damaged the Poltergust 3000? Don't worry about it!",
    "Even if that lightning had cooked your goose, your Poltergust 3000 wouldn't even have a scratch! Heh heh!",
    "Hey now, Luigi! What have you found there? Let me see it!",
    "...Oh...Ahh...It's... an Ice Elemental Medal! Now you can use the Ice Element!",
    "Ice Elemental Ghosts are only found in chilly places. You'll probably find them in refrigerators and cold areas like that...",
    "My research shows that they come out of hiding when you approach. Use the L Button to expel Ice Element once you vacuum one of these ghosts up!",
    "If you press the L button all the way, you can shoot out a frigid lump of ice.",
    "Yes-siree. When water gets cold, it freezes, right? Ice can be effective against water. You could use it on water ghosts, for example.",
    "Even a hot bath would get cold pretty quick if you iced it down. Yep, that's a very convenient item you found there, Luigi!",
    "Yowzer! You got another one! You're cruising, Luigi!",
    "Don't get scared stiff, Luigi!",
    "Careful now, Luigi!",
    "Well done, Luigi my boy! This time I have a special bit of information for you!",
    "You've seen small ghosts other than Boos, haven't you? Well I'm pretty sure they're ghosts freed from the paintings of the ghost artist, Van Gore. I had a passel of trouble the first time I captured him...",
    "I know that artists strive to give life to their canvasses, but this guy brought ghosts to life every time he picked up a brush!",
    "Did you see that Boo just give up at the end, Luigi? Your reputation is spreading!",
    "Oh, what a relief! That white mist interrupted your signal. Hmmmm. You seem to have done some serious work there! Why don't you come back to the lab?",
    "We can have dinner while we gaze at these ghost paintings! Tonight I'll make an old family recipe.",
    "Pickled dandelions with barnacles in a diesel marmalade!",
    "Are you done appreciating art for today, Luigi?",
    "This is the gallery. This is where I hang all my paintings... ghost paintings, that is!",
    "When I was young, I designed a machine to turn ghosts into paintings, and I traveled the world collecting 'em. Oh, it was glamorous, I tell you!",
    "Well, then. Now I have to tell you...a horrifying story... The last ghost I caught was No. 22, Boolossus, but there are lots of Boos, and King Boo rallied them all to take revenge upon me! They used my machine to free Boolossus from the painting... then they went and turned all my other portraits back into ghosts, too!",
    "As if that weren't enough, they built a mansion in front of my lab in the space of a single night, and then they all hid inside! If I told anybody else this stuff, they'd probably have me committed!",
    "I'm sure my portrait ghosts are somewhere inside the mansion. I just have to get 'em back!",
    "Just looking?",
    "I designed the Game Boy Horror as a communications terminal. It has all sorts of functions. For example, you can press the Z button to see a list of the items you've picked up. Give it a try after you get some coins. Of course, you'll also be able to see portrait ghosts there once you capture some.",
    "You can also use the Y button to display a map of the mansion. The display will color the rooms as you visit 'em. Check the map if you ever get lost.",
    "Got all that, sonny?",
    "All right, then!",
    "Where will you go, Luigi?",
    "Good luck!",
    "Luigi, you did it! Truly remarkable, my boy! I supplied the Poltergust 3000, but you ran with it all the way to the top, sonny!",
    "You've made me so...SNIFFF...proud...SNORT! Get ahold of yourself, Gadd!",
    "... What's that? You found King Boo? He jumped into a painting of Bowser, you say? He even blew fire at you?",
    "... Well, well... In all my years of ghost research, I've never heard such a fantastical tale! ... And that career spans sixty years, mind you. Why, I still recall starting out as a young whelp who trembled at the mere thought of a ghost, TREMBLED, I say...",
    "Oh, beg your pardon! This old brain goes recollecting every now and then... I could sit down and fill a week spinning ghost yarns. Why, just last...",
    "... Right, well, anyhoo, Luigi! Grab your brother's painting and bring him to the lab! Heh heh heh... The poor little feller's fallen asleep...",
    "He must have just collapsed with relief and exhaustion when he saw you arrive... I'll get the machine ready to return your brother to his former state, all righty? I'll be expecting you both!",
    "This'll mess with your head: All your hard work lasted only a single night! Well done, Luigi!",
    "The mansion those Boos built disappeared into the night, but that treasure seems to be real. I have no interest in such stuff, so go on and keep it all! Use it however you like!",
    "Say what? Enough rattling on about money? I guess we'd better get your brother back then. Of course, your brother's really important, but first we have to take care of these last ghosts!",
    "I'd wager dollars to donuts that nobody but me has such lovely paintings! Heh heh heh!",
    "Ghosts seem to like darkness, and they avoid the light. So if you hit 'em with a flashlight beam all of a sudden, you can stun 'em momentarily! Then it's vacuuming time!",
    "When you see your chance, hold down the R button and tilt the Control Stick in the opposite direction!",
    "Just give it a try. You'll learn more that way than just listening to me yap about it.",
    "Remember, as soon as you see a ghost's heart, that's your chance to vacuum 'em up! While vacuuming, tilt the Control Stick in the opposite direction to bring 'em in!",
    "When that surprised ghost's heart appears, vacuum it with the R Button and the Control Stick. Tilt the Control Stick in the direction opposite the ghost.",
    "Tilt the Control Stick in the opposite direction quickly and repeatedly for the best results! You have to get as close as you can before flashing the light.",
    "Surprise 'em with the light when they get close! Pow! Pow! The more, the better! Got it?",
    "Ghosts love to hide in dark places. Isn't that a hoot? There! Here they come!",
    "Catching ghosts means using the flashlight and the Poltergust 3000 as a team, you get me, young feller?",
    "That'll do! Well, how many did you get?",
    "Whoo-hoo! Nine ghosts! Excellent, Luigi!",
    "Hey, seven ghosts! That's how to do it, Luigi!",
    "Six ghosts? Well done, Luigi!",
];

// Acquired from https://www.mariowiki.com/List_of_Luigi%27s_Mansion_quotes
export const luigi_quotes = [
    "Hello?",
    "MARIO!",
    "MARIOOO?",
    "Mario?",
    "M-M-M-M-Mario?",
    "Way to go, genius. Got the hang of that thing yet?",
    "What a dreadful picture... But that candle next to it might be important...",
    "I'm willing to bet there's something cold in here.",
    "I always preferred the bottom bunk...",
    "Well, at least we won't have a shortage of toilet paper...",
    "Now that's just not my style.",
    "You know... I never noticed how cute those red polka dots look on top!",
    "It's a picture...but I wouldn't call it art.",
    "Simply delightful...",
    "This looks quite old... I wonder how much it would sell for.",
    "Looks ordinary... A little TOO ordinary.",
    "I wonder why only this one's frozen...",
    "I bet I'd look pretty tough wearing one of these...",
    "One really shouldn't open this kind of thing without asking...",
    "Nothing unusual here... Boring!",
    "I don't think I can reach that directly...",
    "Boy, those Boos sure did make a realistic fake mansion...",
    "Now that I look at it-- it's full of moth holes! Yecch!",
    "So much dust! This will never pass the white-glove test!",
    "Well, they sure did pile odds and ends everywhere... Filthy.",
    "I should probably give that a quick vacuuming...",
    "Oh, what's this?! Just how I like it... Nice and clean!",
    "That would be a good spot to hide some savings...",
    "Well, I sure can't read that from here...",
    "I wonder how old this is...",
    "Do Boos wash their faces?",
    "I've been wanting one of these for quite a while...",
    "Oh, wow... I've always wanted one of these!",
    "What kind of picture is this?",
    "I'm quite taken with this...",
    "I really have no use for this...",
    "Not particularly interesting...",
    "Hmmm... Weird...",
    "Awww, poor thing...",
    "How could anyone treat an animal that way? I won't stand for it!!",
    "Oh, what's this?! This would sure fetch a pretty penny...",
    "Looks like something might be in there...",
    "Now, that's a classic. I wonder how much it would sell for.",
    "If you look closely, you can tell it's really just a photograph!",
    "This looks like it might break if I sit on it...",
    "Man, I'm tired... That bed sure looks comfy.",
    "I could just curl up there and sleep until dawn...",
    "Now who is this supposed to be?",
    "Was someone trying to show off or what?",
    "What's this?! Looks fancy!",
    "WAHAHA! Who designed this?!",
    "There's something fishy here...",
    "I really should work out more. Maybe I ought to throw a few quick jabs while I'm here...",
    "I'm not so interested in bikes...",
    "I've always been a good runner...",
    "I don't care much for pointy objects...",
    "It looks old, but I bet it still has a nice tone...",
    "Hmm. Should I play it?",
    "I never could play the piano...",
    "Looks like a fun place to make shadow puppets...",
    "Looks like this hasn't gotten much use of late...",
    "What's this, an antique?",
    "It's a unicorn statue. The horn looks very cool...",
    "Wouldn't it be nice if I could raise carrier pigeons here?",
    "What in the world is this?",
    "This is the kind of thing I would put in the bathroom...",
    "Fabulous!",
    "Exquisite...",
];

export const f_zero_gx_story_quotes = [
    "Help... Aaaargh... Just give me one more chance! (Black Shadow - Prologue)",
    "One more chance is all you get. Win this F-ZERO Grand Prix or - you know the price of failure... (Deathborn - Prologue)",
    "Yes, yes! I can win it this time! I swear! (Black Shadow - Prologue)",
    "Heh, heh, heh, heh... This time, the prize will be MINE hahahahaha! (Black Shadow - Chapter 1)",
    "You stole the prize money from us last time. You will pay for that! (Samurai Goroh - Chapter 2)",
    "That's a fine looking machine you're driving, Falcon. (Samurai Goroh - Chapter 2)",
    "You know the law here in Red Canyon? If you lose the race, you forefit your machine! (Samurai Goroh - Chapter 2)",
    "You can't back down now! The mighty Falcon can't back down from a challenge, now, can he? (Samurai Goroh - Chapter 2)",
    "Let's do it! (Captain Falcon - Chapter 2)",
    "All right then, the first one to that checkpoint over there is the winner. (Samurai Goroh - Chapter 2)",
    "I can't lose in my Fire Stingray, heh heh heh heh heh... (Samurai Goroh - Chapter 2)",
    "Falcon, I'm gonna get you in the Grand Prix! Gaaahhh! (Samurai Goroh - Chapter 2)",
    "Hey, you, what do you want? Wait a minute. What do you think this is? (Unknown - Chapter 3)",
    "What a scam! Bets of two million space credits? HA! What can I do with this ONE COIN? (Silver Neelsen - Chapter 3)",
    "You're the famous Falcon! Please, I beg of you, enter the bet race. (Silver Neelsen - Chapter 3)",
    "Wha-? Wait a -! (Captain Falcon - Chapter 3)",
    "Please, consider it an old man's last request. (Silver Neelsen - Chapter 3)",
    "Just calm down, old man! (Captain Falcon - Chapter 3)",
    "We will shortly be closing registration for the next race. (Intercom - Chapter 3)",
    "T-the next race is going to start! (Silver Neelsen - Chapter 3)",
    "Hey! Where do you think you're taking me? Wait! (Captain Falcon - Chapter 3)",
    "Just perfect! (Silver Neelsen - Chapter 3)",
    "Ha Ha! Here, this is your share. Take it! (Silver Neelsen - Chapter 3)",
    "Once again, Black Shadow is running riot in the Lightning Area. All citizens are advised to evacuate immediately. We repeat: all citizens are advised to evacuate immediately... (Intercom - Chapter 3)",
    "The gangs... (Captain Falcon - Chapter 4)",
    "YAAAAAAAAAHHHH!! (Michael Chain - Chapter 4)",
    "So, you wanna play... (Captain Falcon - Chapter 4)",
    "Ha ha! Guys! The party's just starting! (Michael Chain - Chapter 4)",
    "Oh no! After Falcon! Don't lose him! (Michael Chain - Chapter 4)",
    "Go! Go after him! What are you doing!? (Michael Chain - Chapter 4)",
    "Are you all right? (Captain Falcon - Chapter 5)",
    "Jody's still inside the building! (John Tanaka - Chapter 5)",
    "Wait there. (Captain Falcon - Chapter 5)",
    "Jody! (Captain Falcon - Chapter 5)",
    "Uuugh... Falcon? (Jody Summer - Chapter 5)",
    "Jody! (John Tanaka - Chapter 5)",
    "Black Shadow! (Captain Falcon - Chapter 5)",
    "Falcon! You've come to die? I needn't have wasted time looking for you, then. (Black Shadow - Chapter 6)",
    "Let's settle this at the Grand Prix, not like this, it's the coward's way. (Captain Falcon - Chapter 6)",
    "The coward's way? You make it sound so noble. I just plan to eliminate anyone who stands between me and the prize. Simple as that! (Black Shadow - Chapter 6)",
    "Hahaha! Falcon, Take this! (Black Shadow - Chapter 6)",
    "Aaagh! What are you doing? (Captain Falcon - Chapter 6)",
    "Come out, Blood Falcon! (Black Shadow - Chapter 6)",
    "Are you ready? (Black Shadow - Chapter 6)",
    "Yeah, I'm ready! (Blood Falcon - Chapter 6)",
    "Farewell, Captain Falcon, hahahahahahaha! (Black Shadow - Chapter 6)",
    "You and Blue Falcon can die together. Ha Hahahahaha! (Blood Falcon - Chapter 6)",
    "Ladies and gentlemen, the contestants: the high-flying Medico - Dr. Stewart, the hitman who flies at the speed of sound - Pico, the Japanese warrior - Samurai Goroh, the cyborg returns - Mighty Gazelle, the emperor of brutality - Black Shadow, and the bounty hunter - Captaaaaaaaain Falconnnnnnnnn! (Announcer - Chapter 7)",
    "Huh? (Samurai Goroh - Chapter 7)",
    "Well, still alive it seems? But I won't miss this chance to make mincemeat of you, hahahaha! (Black Shadow - Chapter 7)",
    "Black Shadow, I'll show you! You'll never beat me! (Captain Falcon - Chapter 7)",
    "Ladies and gentlemen, start your engines! (Announcer - Chapter 7)",
    "Our champion, Captain Falcon! (Announcer - Chapter 7)",
    "The F-ZERO committee will now present the champion's prize belt. (Announcer - Chapter 7)",
    "What the...? Agh... (Black Shadow - Chapter 7)",
    "Black Shadow, you failed again, you good-for-nothing... (Deathborn - Chapter 7)",
    "AAARGH! Forgive me, Lord Death! AAAAAAAAARGH!! (Black Shadow - Chapter 7)",
    "Ju...just who are you? (Captain Falcon - Chapter 7)",
    "I am Deathborn, the Grand Prix Champion of the Underworld. Why don't you and I race each other tomorrow? Surely, as champion, you have to accept! Muahahahaha! (Deathborn - Chapter 7)",
    "I've been waiting for you. Did you bring the champion's belt? (Deathborn - Chapter 8)",
    "Good. (Deathborn - Chapter 8)",
    "Falcon, shall I tell you something before you die? (Deathborn - Chapter 8)",
    "Dark and Light: the two great forces which make up our universe. These two universal forces are condensed in each of our belts. (Deathborn - Chapter 8)",
    "Didn't you know? (Deathborn - Chapter 8)",
    "At the moment when the two forces become one, it is possible to seize that power. Then, I can turn this whole galaxy into a pile of ashes in an instant! (Deathborn - Chapter 8)",
    "How I've waited for this moment. The world will fall into total darkness... (Deathborn - Chapter 8)",
    "Not if I can help it, I'll destroy you yet! Let's go! (Captain Falcon - Chapter 8)",
    "AAAAAAaaaaaaargh! No, it can't be! How can I lose? Nooooooooooooo...! (Deathborn - Chapter 8)",
    "The evil forces will never get their hands on this belt! I'll keep winning! (Captain Falcon - Chapter 8)",
    "Falcon... Hahahahaha... Falcon... Hehehehehehe... Look, I'm over here, Falcon! Hahohohoho... (\"The Creators\" - Chapter 8)",
    "Who are you? (Captain Falcon - Chapter 9)",
    "We are the Creator (\"The Creators\" - Chapter 9)",
    "What are you talking about? (Captain Falcon - Chapter 9)",
    "Mhmmheh... We created the whole world! (\"The Creators\" - Chapter 9)",
    "What a surprise you'd beat Deathborn, our best creation. (\"The Creators\"- Chapter 9)",
    "Your best creation...? (Captain Falcon - Chapter 9)",
    "So, it was you who set up everything... But why? (Captain Falcon - Chapter 9)",
    "To tell you the truth, there are no universal forces. (\"The Creators\"- Chapter 9)",
    "What!? (Captain Falcon - Chapter 9)",
    "Now you have become the champion of the two Grand Prix... we'll take out your soul from your body and turn it into our creation. (\"The Creators\"- Chapter 9)",
    "Are you ready? Hahahahaha! (\"The Creators\"- Chapter 9)",
    "Come off it! You think YOU can beat ME? No way! (Captain Falcon - Chapter 9)"
];